### ISSUE TITLE
Tool not set for furniture

### ISSUE THREAD

**Issue by aNinjin** [ApexStudios-Dev/FantasyFurniture#23]
As shown below, it seems to be missing a tool tag. (Unless that's what you want)

![Screenshot 2022-07-03 110644](https://user-images.githubusercontent.com/106577745/177051995-a99a1ac0-f76b-4157-8a86-3d151ae50456.png)

**Comment by ApexModder** [comment]
This is indeed a bug and will be fixed in the next update.
The _Nordic_, _Dunmer_ & _Venthyr_ FurnitureSet Blocks sets will be marked as `#minecraft:mineable_with_axe` (Excluding _Wool_ & _Carpet_ Blocks for obvious reasons)
