### ISSUE TITLE
[1.16.5] Requires Registrator when mod page only says ApexCore

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ApexStudios-Dev/FantasyFurniture#24]
Unfortunately due to a mod call it has become unusable because it wants registrator instead of apexcore. 
![Overwolf_24QHyywR2g](https://user-images.githubusercontent.com/10351221/178640423-a8a4e461-7eaf-4346-a176-98a634e716b0.png)
![Overwolf_n12KA6T6kn](https://user-images.githubusercontent.com/10351221/178640453-a0d435db-1aa0-4449-b670-fce0a8f98f99.png)

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:74) ~[?:?] {re:classloading}
-- MOD fantasyfurniture --
Details:
	Mod File: fantasyfurniture-1.16.5-2.0.2.jar
	Failure message: Mod fantasyfurniture requires registrator 1.4.2 or above, and below 2.0.0
		Currently, registrator is not installed
	Mod Version: 2.0.2
	Mod Issue URL: https://github.com/ApexStudios-Dev/FantasyFurniture/issues
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by ApexModder** [comment]
versions compiled for **1.16.5** still depend on and require **Registrator**, besure you have it installed when playing on **1.16.5**.

Our mods used to require both _Registrator_ & _ApexCore_ but during update process to _1.18_ this was changed and _Registrator_ was merged into _ApexCore_ but old legacy versions (_1.16.5_) still require _Registrator_ to be installed.
