### ISSUE TITLE
Bone Bookshelf causing server crash

### ISSUE THREAD

**Issue by Bluemagelord** [ApexStudios-Dev/FantasyFurniture#25]
One of my players tried opening the book bookshelf and our server crashed - twice. Once with an older version of the mod and then again with the most recent edition. 

Crash report sent to dev. and here's another copy. 

[crash-2022-07-17_18.27.31-server.txt](https://github.com/ApexStudios-Dev/FantasyFurniture/files/9128346/crash-2022-07-17_18.27.31-server.txt)

**Comment by ApexModder** [comment]
This can be fixed byh simply breaking & replacing the bookshelf block.
Issue was cause by the update that increased the amount of slots the bookshelves have.
