### ISSUE TITLE
Stackable decorations only drop one item

### ISSUE THREAD

**Issue by ChloeDawn** [ApexStudios-Dev/FantasyFurniture#27]
**Mod version:** [1.18.2-3.6.0](https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture/files/3877690)

When a decoration such as the chocolate muffins are stacked to 2 or 3 and then broken, only one item is dropped even though multiple were placed in that block space.

**Comment by ApexModder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stackables only dropping 1 item, when they should drop how ever many are placed in the stack.](https://trello.com/c/gLBmNehY/2-stackables-only-dropping-1-item-when-they-should-drop-how-ever-many-are-placed-in-the-stack)

**Comment by ApexModder** [comment]
Fixed in versions _**1.18.2-3.6.1**_ & _**1.19-4.2.1**_
