### ISSUE TITLE
[1.18.2] JEI Version requirement issues

### ISSUE THREAD

**Issue by Sweed-Le-Deedly** [ApexStudios-Dev/FantasyFurniture#29]
While this new update downported the Royal update from 1.19.2, it also downported the JEI requirements for the 1.19.2 version.

The mod is looking for JEI versions 10.1.3+, but those versions are only for 1.19.2. Not only that, but this has also went into then new version of ApexCore, though I do know that this isn't the place to report versions for that.

-- MOD fantasyfurniture --
Details:
	Mod File: /C:/Users/TJ/AppData/Roaming/.minecraft/mods/fantasyfurniture-1.18.2-3.8.0.jar
	Failure message: Mod fantasyfurniture only supports jei 10.1.3.+ or above
		Currently, jei is 9.7.1.255
	Mod Version: 3.8.0
	Mod Issue URL: https://github.com/ApexStudios-Dev/FantasyFurniture/issues
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD apexcore --
Details:
	Mod File: /C:/Users/TJ/AppData/Roaming/.minecraft/mods/apexcore-1.18.2-4.11.1.jar
	Failure message: Mod apexcore only supports jei 10.1.3.+ or above
		Currently, jei is 9.7.1.255
	Mod Version: 4.11.1
	Mod Issue URL: https://github.com/ApexStudios-Dev/ApexCore/issues
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by ApexModder** [comment]
1.18.2 requires an alpha version of JEI
https://github.com/ApexStudios-Dev/FantasyFurniture/blob/1.18.2/src/main/resources/META-INF/mods.toml#L53 - Shows the version of JEI required `10.1.3.+` (or newer)
[This version](https://www.curseforge.com/minecraft/mc-mods/jei/files/3904349) world work fine

This is the case as we make use of JEI's newer API changes which only exist in the alpha versions on 1.18.2 and are the only API on 1.19.2

**Comment by superdude808** [comment]
um... https://www.curseforge.com/minecraft/mc-mods/jei/files/3940240  is the latest JEI version for 1.18.2 so... 
the point still stands that the mod is asking for an old version of JEI and not accepting the new one as valid

**Comment by ApexModder** [comment]
We require an alpha version of JEI due to the downports from 1.19.2 using the newer API changes which only exist in the alpha versions on 1.18.2.

We could go through and change to use more stable version but that would require more work than we want to put into 1.18.2.
1.18.2 is our LTS version, it receives critical bug fixes & downports of finished features from 1.19.2

**Comment by ApexModder** [comment]
So I was under the impression that JEI's API changed a lot more than I thought it did, just tried using a more stable version `9.7.1.232` which loaded and ran fine with no code changes required.

An update is in the process of being compiled & released to make use of this more stable JEI version.

**Comment by Corosauce** [comment]
Thanks for the revert, without that we wouldn't be able use your mod updates on 1.18.2, that alpha build of JEI breaks other mods integrations as it seems to contain changes they need to support, for example tinkers fluid recipes and herexei cauldron recipes dissapear, and for some their game crashes if they try to use their simple network storage mod stuff.
