### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Uniqeues** [ApexStudios-Dev/FantasyFurniture#31]
Hi i've tried to install fantasy furniture for version 1.19 forge on forge server 1.19 and it didn't work. It didn't even start the server. Could you help me?

**Comment by ApexModder** [comment]
Please provide any log files you may have, without log files it's next to impossible to help.
They provide the context into how & where errors are occurring.

**Comment by ApexModder** [comment]
Closed as no response was given.
